"""First migration

Revision ID: 03e6d9cbfec3
Revises: 6469fe1eeb9f
Create Date: 2023-07-23 11:49:50.308556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e6d9cbfec3'
down_revision = '6469fe1eeb9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
