"""Added account table

Revision ID: 07eaabba1a7a
Revises: b97db6f4d9f9
Create Date: 2023-07-22 13:58:35.059711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07eaabba1a7a'
down_revision = 'b97db6f4d9f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('path_img', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('window',
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.Column('character', sa.String(length=100), nullable=True),
    sa.Column('path_img', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('window_id')
    )
    op.drop_table('screens')
    op.drop_table('scenes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('scenes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('img', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scenes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('screens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('characters', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('img', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name='screens_scene_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='screens_pkey')
    )
    op.drop_table('window')
    op.drop_table('scene')
    # ### end Alembic commands ###
