"""First

Revision ID: 3f151e7ce588
Revises: 03e6d9cbfec3
Create Date: 2023-07-23 15:37:00.663944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f151e7ce588'
down_revision = '03e6d9cbfec3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
