"""update table

Revision ID: aa7ccc8f863c
Revises: 07eaabba1a7a
Create Date: 2023-07-22 16:34:48.573829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7ccc8f863c'
down_revision = '07eaabba1a7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('window', sa.Column('position', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('window', 'position')
    # ### end Alembic commands ###
